name: playpal
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  flutter_datetime_picker_plus: ^2.1.0
  latlong2: ^0.9.0
  animated_text_kit: ^4.2.1
  firebase_core: ^2.27.2
  firebase_database: ^10.4.11

  intl: any
  flutter_gen: any
  url_launcher: any
  google_maps_flutter: ^2.6.0
  flutter_ui_toolkit: ^0.0.3+9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/event_list.json
    - assets/user.json
