name: playpal
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  intl: ^0.19.0
  lints: ^3.0.0
  matcher: ^0.12.16+1
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  path: ^1.9.0
  test_api: ^0.7.0
  web: ^0.5.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/event_list.json
    - assets/user.json
