// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcdbz2GtK-IJ4BQzrP3BE5_32WTS3go68',
    appId: '1:143290992422:web:fec10859656db5984ae3e7',
    messagingSenderId: '143290992422',
    projectId: 'playpal-78628',
    authDomain: 'playpal-78628.firebaseapp.com',
    storageBucket: 'playpal-78628.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr7rpNDA1DWD8Z0FnDf8nPUZAdMC0gNPE',
    appId: '1:143290992422:android:1458bb2b421d43c84ae3e7',
    messagingSenderId: '143290992422',
    projectId: 'playpal-78628',
    storageBucket: 'playpal-78628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlaJhkjUqOiPnSSWRxC5faPKGbEtvQ8s',
    appId: '1:143290992422:ios:6a1710bcf7150e4f4ae3e7',
    messagingSenderId: '143290992422',
    projectId: 'playpal-78628',
    storageBucket: 'playpal-78628.appspot.com',
    iosBundleId: 'com.testing.myplaypal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYlaJhkjUqOiPnSSWRxC5faPKGbEtvQ8s',
    appId: '1:143290992422:ios:eb35a5a8a8d0cd304ae3e7',
    messagingSenderId: '143290992422',
    projectId: 'playpal-78628',
    storageBucket: 'playpal-78628.appspot.com',
    iosBundleId: 'com.example.playpal.RunnerTests',
  );
}
